### ISSUE TITLE
Sprint: Break down data display for each page -- Story Points: 3

### ISSUE THREAD

**Issue by Rosebud303** [Halo-Omega/Halo-Omega#11]
Description: Split up pages and define what data we need to present on each page. Use api and halotracker.com as reference points to better define data display.

**Comment by J-Poulter** [comment]
[Completed Data Map](https://docs.google.com/spreadsheets/d/1yz4_xNXTJk5-OVNwkSizyvf6sIlFtIQrGuJg9hf4pIg/edit#gid=0)

Will likely need to be updated when additional elements are added such as individual player card for individual matches and possible campaign stats section.

@Rosebud303 @J-Poulter
